# Generated by Django 2.1 on 2019-05-31 13:09

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190531_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('context', models.FileField(upload_to=tasks.models.context_file_path)),
                ('download_url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.FileContext'),
        ),
    ]
