# Generated by Django 2.1 on 2019-05-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190531_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='download_url',
        ),
    ]
