# Generated by Django 2.1 on 2019-05-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_download_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='context',
            new_name='filecontext',
        ),
    ]
