# Generated by Django 2.1 on 2019-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_auto_20190527_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='download_url',
            field=models.TextField(default='kreker'),
            preserve_default=False,
        ),
    ]
