# Generated by Django 2.1 on 2019-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_stack_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='year_in_school',
            field=models.CharField(choices=[('ERR', 'Error'), ('ENQ', 'Enqueued'), ('PSH', 'Successfully built and pushed')], default='PS', max_length=2),
            preserve_default=False,
        ),
    ]
