# Generated by Django 2.1 on 2019-05-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_auto_20190529_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='error_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
