# Generated by Django 2.1 on 2019-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0008_auto_20190529_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('error', 'Error was occurred while processing'), ('enqueued', 'Enqueued'), ('pushed', 'Successfully built and pushed'), ('processing', 'Processing')], max_length=2),
        ),
    ]
