# Generated by Django 2.1 on 2019-06-07 20:31

from django.db import migrations, models
import stacks.models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0010_auto_20190529_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='config',
            field=models.FileField(blank=True, default=None, null=True, upload_to=stacks.models.config_file_path),
        ),
    ]
