# Generated by Django 2.1 on 2019-06-04 21:38

from django.db import migrations, models
import filecontexts.models


class Migration(migrations.Migration):

    dependencies = [
        ('filecontexts', '0004_auto_20190604_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontext',
            name='dc_file',
            field=models.FileField(blank=True, default=None, upload_to=filecontexts.models.dc_file_path),
        ),
    ]
