# Generated by Django 2.1 on 2019-06-04 21:39

from django.db import migrations, models
import filecontexts.models


class Migration(migrations.Migration):

    dependencies = [
        ('filecontexts', '0005_auto_20190604_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontext',
            name='dc_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=filecontexts.models.dc_file_path),
        ),
    ]
