# Generated by Django 2.1 on 2019-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion
import task_instances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_auto_20190605_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('added', 'Added to database'), ('enqueued', 'Enqueued for processing'), ('deploying', 'Deploying in progress'), ('deployed', 'Deployed'), ('error', 'Error was occurred'), ('undeploying', 'Undeploying in progress')], max_length=10)),
                ('dc_config', models.FileField(upload_to=task_instances.models.task_instance_dc_file_path)),
                ('error_text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task')),
            ],
        ),
    ]
