# Generated by Django 2.1 on 2019-06-05 16:35

from django.db import migrations, models
import django.db.models.deletion
import task_instances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_auto_20190605_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_config', models.FileField(upload_to=task_instances.models.ti_dc_file_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task')),
            ],
        ),
    ]
